# Setup
title:        蘑菇的小屋
tagline:      蘑菇的个人博客
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       fanny2011
  url:        https://github.com/fanny2011/ 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
